package main

var Dict = []string{

	// 01
	"paradox: n.悖论",
	"parachute: n.降落伞 v.跳伞，空投",
	"paralysis: 麻痹，瘫痪",
	"estate: n. 地产；庄园；住宅区；遗产，财产；状况，状态",
	"steer: v. 驾驶；指导，引导",
	"sheer: adj. 纯粹的，完全的，陡峭的",
	"accord: n.协议，条约  v.相符合",
	"publicize: v.引起...注意，宣传",
	"publication: n.出版物",
	"curb: v.控制，抑制  n.限制，控制",
	"chancellor: n.大臣，总理",
	"humane: adj.人道的",
	"anthropology: n.人类学",
	"anthropologist: n.人类学家",

	//02
	"conscience: n. 良心, 良知",
	"means: n. 方法, 手段",
	"regime: n. 政体, 政权",
	"indifferent: adj. 冷漠的, 不关心的",
	"found: v. 建立, 创立",
	"foundation: n. 基础, 基本原理, 基金会",
	"erect: v. 建造, 建立  adj. 垂直的",
	"pioneering: adj. 开创性的, 探索性的",
	"repay: v. 偿还, 报答",
	"installment: n. 分期付款",
	"displace: v. 移动...的位置, 取代",
	"servant: n. 仆人, 雇员",
	"deserve: v. 应受, 值得",
	"preserve: v. 保护, 维护  n. 独占区, 保护区 ",
	"reserve: n. 保留, 储备金, 储备  v. 保留, 预定",
	"reserved: adj. 有节制的",
	"conservation: n. 保护",
	"conservative: adj. 保守的, 守旧的  n. 保守者",
	"abide: v. 停留, 遵守",
	"glimpse: n. 一瞥",
	"gaze: v/n 凝视",
	"glare: v/n. 怒视",
	"creature: n. 人, 生物, 产物",
	"concrete: adj. 具体的  n. 混凝土",
	"procreation: n. 生育",
	"recreation: n. 娱乐, 消遣",
	"cultivate: v. 耕作, 培养, 栽培",
	"cultivation: n. 培养, 教养, 培植",
	"reform: v/n. 改革, 改造, 改良",
	"form: n. 形式, 表格, 形成  v. 形成",
	"formation: n. 形成, 组成, 编队",
	"formal: adj. 正式的, 正规的",
	"formula: n. 公式, 方程式, 准则, 方案",
	"formulate: v. 构想出, 规划",
	"formidable: adj. 可怕的, 令人敬佩的",
	"informed: adj. 了解情况的",
	"performative: adj. 表述行为的",
	"conform: v. 适应, 顺从, 服从, 相符合",
	"conformity: n. 一致, 符合, 遵照",
	"former: adj. 以前的, 在前的  n. 前者",
	"reproduce: v. 生殖, 繁殖",
	"toll: n. 通行费, 长途电话费, 不良影响  v. 向...征税",
	"diligent: adj. 勤奋的, 勤勉的",

	// 03
	"exclusive: adj. 独家的, 独占的",
	"conclude: v. 下结论",
	"conclusion: n. 结论",
	"inconclusive: adj. 无法决断的, 不确定的",
	"naive: adj. 年轻的, 幼稚的",
	"distress: v. 使苦恼  n. 苦恼, 危难",
	"emphasize: v. 强调",
	"emphasis: n. 强调, 重视",
	"perspective: n. 透视图, 远景, 想法, 态度, 角度",
	"roundabout: adj. 迂回的 n.环形交叉口",
	"backyard: n. 后院",
	"feedback: n. 反馈, 反馈意见",
	"backdrop: n. 背景, 背幕",
	"backload: v. 增加费用",
	"expertise: n. 专业知识, 专场",
	"empirical: adj. 经验的",
	"plead: v.. 恳求, 辩护",
	"plea: n. 抗辩, 恳求, 托词",
	"pledge: n. 誓约, 保证",
	"estimate: v. 估计, 评估, 估量",
	"assess: v. 评价, 评论",
	"patent: n. 专利",
	"monopoly: n. 垄断, 专卖",
	"provided: conj. 除非, 假若, 以...为条件",
	"provision: n. 供应, 提供, 条款, 储备物",
	"render: v. 使成为, 使变得",
	"refund: v. 退还, 偿还",
	"profound: adj. 根深蒂固的, 影响深远的",
	"entrenched: adj. 根深蒂固的",
	"consider: v. 认为, 考虑",
	"considerable: adj. 深思熟虑的",
	"considerably: adv. 相当地, 可观地",
	"contemplate: v. 盘算, 预测, 思量",
	"assume: v. 认为, 假定",
	"assumption: n. 假设, 臆测",
	"resume: v. 恢复",
	"presumably: adv. 推测起来, 大概",
	"concern: v. 关心",
	"concerning: prep. 关于",
	"discern: v. 认出, 觉察出",
	"mill: n. 磨坊",

	// 04
	"extraordinary: adj. 意想不到的, 令人惊奇的, 特别的",
	"compress: v. 压紧, 压缩",
	"suppress: v. 镇压, 抑制",
	"oppressive: adj. 压迫的, 不公的",
	"impression: n. 印象",
	"impressive: adj. 印象深刻的",
	"depression: n. 抑郁, 沮丧",
	"compact: adj. 紧凑的, 小型的  v. 把...压实  n. 契约",
	"profile: n. 侧面, 轮廓, 外形, 形象, 印象",
	"attend: v. 出席, 陪同, 参加, 照料, 注意",
	"attendant: n. 服务员  adj. 伴随的, 附带的",
	"attendance: n. 出席, 出席人数, 参加, 照顾",
	"significance: n. 意义, 重要性",
	"significant: adj. 有意义的, 显著的, 数量大的",
	"signature: n. 签名",
	"signify: v. 意味着",
	"designate: v. 把...定名为, 指定, 标明",
	"endorse: v. 赞同, 支持, 宣传",
	"craft: n. 工艺, 手艺, 飞机, 技巧  v. 精心制作",
	"bend: v. 使弯曲",
	"commute: v/n. 通勤",
	"threshold: n. 门槛",
	"excess: n. 过量  adj. 过量的, 额外的",
	"excessive: adj. 过多的, 过分的",
	"concession: n. 让步, 妥协",
	"recession: n. 衰退, 萧条",
	"transplant: v. 移植, 使迁移",
	"transaction: n. 交易, 业务",
	"transparent: adj. 透明的, 明晰的, 公开的",
	"transient: adj. 短暂的, 暂时的",
	"transition: n. 转变, 过渡",
	"setback: n. 挫折, 倒退, 失败",
	"ideology: n. 意识形态",
	"",

	// 09
	"agenda: n.议事日程，动机",
	"upset: n.翻到，倾覆，混乱，苦恼，困扰 v.使心烦意乱",
	"upsetting: adj.令人心烦的，令人苦恼的",
	"crisis: n.危机",
	"hypocritical: adj.虚伪的，伪善的",
	"offset: v.抵消，弥补",
	"criterion: n.准则，（评判）标准",
	"condemn: v.谴责",
	"retail: n.零售",
	"entail: v.使成为必要，牵扯",
	"tailor: n.裁缝 v.裁制",
	"drug: n.药物，毒品 v.使服用麻醉药",
	"dose: n.剂量，一剂，一次，一服，一回 v.服药",
	"coexistence: n.共存,共处",
	"handful: n.一把,几个,难管的人",
	"handy: adj.有用的,手边的",
	"handicap: v.妨碍,使不利",
	"cope: v.竞争,对抗,处理",
	"landscape: n.风景, 景色",
	"landmark: n.地标",
	"landlord: n.房东",
	"meadow: n.牧场, 草地",
	"mass: n.团, 块, 堆, 群众, 大量, 质量, 大多数 adj.大多数的",
	"massive: adj. 大规模的, 大量的",
	"vastly: adv. 很, 非常",
	"utmost: adj. 极限的, 最远的, 极度的 n.极限, 极度, 最大可能",
	"protein: n.蛋白质",
	"succession: n. 连续, 一连串, 继承, 继任",
	"successive: adj. 连续的",
	"survey: v. 审查, 考察, 测量 n. 调查, 考量, 概述",
	"scrutiny: n. 监督, 审查",
	"scrutinize: v. 仔细检查",
	"supervise: v. 管理, 监督, 指导",
	"supervision: n. 监督, 管理",
	"monitor: n. 班长 v. 监控, 监督",
	"undergo: v. 经历, 遭受",
	"underlying: adj. 潜在的, 深层的, 根本的, 表面下的",
	"association: n. 社团, 协会, 联系, 联合",
	"associate: v. 联系, 交往  n. 合作人, 伙伴  adj. 副的",
	"prevail: v. 获胜, 流行",
	"prevailing: adj, 普遍的, 流行的",
	"conversation: n. 交谈",
	"avert: v. 避免, 防止",
	"adverse: adj. 不利的, 有害的, 敌对的",
	"vertical: adj. 垂直的  n. 垂直线",
	"divert: v. 转移, 绕道",
	"diverse: adj. 多种多样的",
	"diversity: n. 多样性",
	"convert: v. 转变",
	"invert: v. 颠倒, 倒置",

	// 10
	"neglect: v. 忽视, 忽略  n.忽视, 疏忽",
	"peculiar: adj. 特殊的, 古怪的",
	"reception: n. 接待, 接收",
	"receipt: n. 收据, 收条",
	"perceive: v. 察觉, 意识到, 认为",
	"perception: n. 察觉",
	"conceive: v. 构想, 怀孕, 设想",
	"correlate: n. 关联的人  v. 相互关联",
	"correlation: n. 相关性",
	"relative: adj. 相关的, 相对的",
	"kin: n. 家族, 家属  adj. 亲属关系的",
	"narrative: adj. 叙事的, 有故事性的  n. 叙述, 记叙文",
	"apply: v. 申请, 应用",
	"applicant: n. 申请者",
	"conduct: n. 行为, 举止, 引导, 实施  v. 安排, 组织",
	"conductor: n. 指挥, 售票员",
	"semiconductor: n. 半导体",
	"sip: v. 小口的喝, 抿",
	"unexpected: adj. 意外的, 想不到的",
	"identical: adj. 同样的, 同一的",
	"recognize: v. 认出, 承认",
	"recognition: n. 认出, 识别",
	"cognitive: adj. 感知的, 认知的",
	"acquaintance: 你. 认识的人, 相识, 了解",
	"outcome: n. 结果",
	"hail: v. 来自, 欢迎, 下冰雹 n. 冰雹",
	"wage: v. 进行, 开始  n. 工资, 报酬",
	"insure: v. 上保险, 保证",
	"ensure: v. 确保, 保证",
	"assure: v. 使确信, 向...保证",
	"assurance: n. 保证, 担保",
	"invest: v. 投资, 投入",
	"investigate: v. 调查, 审查",
	"liberty: n. 自由",
	"liberal: adj. 自由的",
	"liberate: v. 解放, 释放",
	"compromise: v. 妥协, 让步",
	"stick: n. 棍, 枯枝, 棍状物  v. 刺, 粘贴, 忍受, 放置, 卡住",
	"glue: n. 胶水  v. 粘贴",

	// 11
	"affectionate: adj. 有感情的",
	"characteristic: adj. 典型的, 独特的  n. 特征, 特性",
	"characterize: v. 表示...的特性",
	"characterization: n. 人物塑造, 角色刻画",
	"figure: n. 人物, 形象, 数字, 图形  v. 计算, 认为, 描绘, 象征",
	"complementary: adj. 互补的",
	"complement: v. 补充, 补足  n. 补充, 补足物",
	"thoroughly: adv. 彻底地",
	"contributory: adj. 促成的, 促进的",
	"contributor: n. 投稿人, 捐款人, 促成因素, 原因之一",
	"distribute: v. 分配, 分布, 分开",
	"distribution: n. 分配, 分布, 传播",
	"tribute: n. 贡品, 体现, 颂词",
	"permeate: v. 弥漫, 散步",
	"corporate: adj. 公司的, 团体的, 法人的",
	"corporation: n. 公司, 社团",
	"incorporate: v. 把...合并, 使并入",
	"currency: n. 货币, 通货",
	"curriculum: n. 课程",
	"curve: n. 曲线  v. 弯曲",
	"trend: n. 趋向, 趋势  v. 倾向, 趋向",
	"tide: n. 潮汐, 潮流, 趋向",
	"exploit: v. 开发, 开拓, 运用, 剥削, 压榨",
	"functioning: n. 运行, 机能, 功能",
	"functionalism: n. 功能主义, 实用主义",
	"grant: v. 同意, 准予, 授予  n. 授予, 拨款",
	"grand: adj. 宏伟的",
	"majestic: adj. 宏伟的, 庄严的",
	"locate: v. 使...坐落于, 找到",
	"allocate: v. 分配, 分派",
	"allocation: n. 拨款, 分配的东西, 分配",
	"materialistic: adj. 物质至上的, 拜金的",
	"stuff；n. 东西, 原料, 材料  v. 把...填满",
	"substance: n. 物质, 物品, 重要性, 要点",
	"privacy: n. 隐居, 隐私",
	"deprive: v. 剥夺, 使丧失",
	"arrange: v. 安排, 准备, 排列, 布置, 谱写",
	"suit: n. 西服, 诉讼  v. 对...方便, 合...心意, 适合",
	"threaten: v. 恐吓, 威胁",
	"hazard: n. 危险, 危害  v. 冒...的险, 斗胆提出",
	"reckless: adj. 鲁莽的, 草率的",
	"regardless: adv. 不管, 不顾, 毫不在意地",
	"nevertheless: adv. 仍然, 不过",
	"nonetheless: adv. 尽管如此, 但是",
	"whereas: conj. 然而, 尽管, 但是",
	"despite: prep. 尽管",
	"lest: conj. 唯恐, 免得",
	"liability: n. 责任",
	"appetite: n. 食欲, 胃口, 欲望",
	"competitive: adj. 竞争的, 有竞争力的",
	"competent: adj. 有能力的",
	"incompetently: adv. 不称职的",
	"rival: n. 竞争对手  v. 比得上  adj. 竞争的, 对立的",
	"manufacture: v. 量产, 生产  n.产品, 制造",
	"manufacturer: n. 制造商",
	"manufacturing: n. 制造业",

	// 12
	"respectable: adj. 受人尊敬的",
	"respective: adj. 各自的, 单独的",
	"esteem: v/n. 尊重, 尊敬",
	"rescue: v/n. 营救, 救援",
	"infrastructure: n. 基础结构",
	"restructure: v.重建, 重组",
	"construct: v. 建造, 构造",
	"instruct: v. 教, 讲授, 命令, 指示",
	"enterprise: n. 产业, 企业, 事业",
	"astonish: v. 使惊讶, 使惊奇",
	"dazzle: v. 使惊奇, 耀(眼), 刺眼",
	"dazzlingly: adv. 灿烂的, 辉煌的",
	"stunning: adj. 令人惊奇的, 令人震惊的",
	"academic: adj. 学术的",
	"fulfill: v. 完成, 履行, 实践",
	"fulfillment: n. 成就感, 完成, 实现",
	"accomplish: v. 完成, 实现",
	"consequence: n. 结果, 后果, 推论, 重要性",
	"consequently: adv. 因此, 所以",
	"sequence: n. 先后, 次序, 连续",
	"subsequent: adj. 随后的",
	"subsequently: adv. 随后, 后来",
	"contention: n. 争吵, 争论",
	"emerge: v. 出现, 暴露, 显现",
	"emergence: n. 浮现, 出现",
	"immersive: adj. 沉浸式的",
	"furthermore: adv. 此外, 而且",
	"institution: n. 公共机构, 习俗, 制度, 建立",
	"institute: v. 建立, 制定, 开创",
	"interpret: v. 解释, 说明",
	"interim: n. 间歇, 过渡期  adj. 暂时的, 临时的, 过渡的",
	"interfere: v. 干预, 干涉, 介入",
	"intervene: v. 插手, 介入, 干预",
	"trial: n. 审讯, 实验, 比赛",
	"postmodern: adj. 后现代主义的",
	"principal: adj. 主要的  n. 负责人, 首长, 本金",
	"race: n. 比赛, 竞争, 种族, 民族",
	"ethnic: adj. 种族的, 异族的",
	"reward: n. 回报, 酬金, 奖赏",
	"award: n. 奖项, 奖品, 奖金",
	"steward: n. 管家",
	"ward: n. 病房, 行政区  v. 保护",
	"wardrobe: n. 衣橱",
	"garment: n. (一件)衣服",
	"lottery: n. 彩票, 抽奖",
	"dissolve: v. 溶解, 解散, 终止, 消除",
	"resolve: v. 解决  n. 决议, 决定, 表决, 溶解",
	"resolute: adj. 坚决的, 坚定的",
	"resolution: n. 决定, 决心, 决意",
	"authority: n. 专家, 权威, 官方",
	"authentic: adj. 真的, 真正的, 可靠的",
	"authenticate: v. 证实",
	"bore: v. 钻孔, 挖通道, 使厌烦, 盯着看  n. 令人厌烦的人, 烦事, 孔",
	"border: n. 边界, 边缘  v. 成为...的界线",
	"examine: v. 检查, 调查",
	"undermine: v. 削弱, 损害, 破坏",
	"edition: n. 版本, 版次",
	"editorial: n. 社论  adj. 编辑的",
	"draft: n. 草稿  v. 起草",
	"column: n. 圆柱, 专栏",
	"deploy: v. 调动, 利用",
	"elevate: v. 提高, 举起",
	"alleviate: v. 减轻, 缓和, 缓解",
	"augment: v. 扩大, 增加, 提高",

	// 13
	"forge: v. 锻造, 伪造  n. 锻造车间, 锻炉",
	"stove: n. 火炉",
	"giant: adj. 特大的  n. 巨人, 巨物",
	"infant: n. 幼儿, 婴儿  adj. 婴儿用的, 初期的, 初创的",
	"orphan: n. 孤儿",
	"deem: v. 认为, 视为",
	"deed: n. 行为, 行动, 功绩, 契约",
	"fertilizer: n. 肥料",
	"senate: n. 上议院, 元老院",
	"senator: n. 参议院",
	"abstract: adj. 抽象的  v. 提取, 抽取, 分离  n. 摘要, 梗概",
	"extract: v. 提炼, 提取  n. 提取物, 精, 汁, 摘录",
	"distract: v. 分散(注意力), 使分心, 迷惑, 扰乱",
	"contract: v. 缩小, 使收缩 n. 契约, 合同",
	"contractor: n. 承包商",
	"contraction: n. 收缩, 缩小",
	"conscious: adj. 意识到, 有意的",
	"conscience: n. 良知",
	"unconsciously: adv. 未意识到地",
	"aware: adj. 知道的, 意识到的",
	"deliberate: adj. 故意的, 深思熟虑的",
	"seldom: adv. 很少",
	"wisdom: n. 智慧, 看法, 一般观点",
	"heal: v. 愈合, 和解",
	"upheaval: n. 动荡, 动乱",
	"innovation: n. 创新, 改革",
	"novel: n. 长篇小说  adj. 新奇的, 新颖的",
	"fiction: n. 虚构小说",
	"pharmaceutical: adj. 制药的, 药物的",
	"progression: n. 发展, 进程",
	"projection: n. 预算, 估算, 投射",
	"slum: n. 贫民窟",
	"administer: v. 治理",
	"atmosphere: n. 大气层",
	"aerial: adj. 航空的",
	"aviation: n. 航空, 飞行",
	"wing: n. 翅膀, 耳房, 侧翼",
	"tempt: v. 引诱, 鼓动, 诱惑",
	"aesthetic: adj. 美学的, 艺术的",
	"campaign: n. 战役, 运动",
	"campus: n. 大学校园",
	"camp: n. 野营",
	"classic: n. 艺术杰作, 文学名著",
	"royal: n. 皇家的, 皇室的",
	"commission: n. 委员会, 委托, 请求, 佣金, 手续费, 犯罪  v. 委托, 委任",
	"committee: n. 全体委员",
	"commit: v. 犯罪, 承诺",
	"commitment: n. 承诺, 责任, 风险",
	"submit: v. 屈服, 顺从, 投降, 提交",
	"complicated: adj. 复杂的",
	"perplexing: adj. 复杂的, 令人困惑的",
	"intricate: adj. 错综复杂的",

	// 14
	"doubt: v. 无把握, 怀疑  n.怀疑",
	"joy: n. 快乐, 喜悦, 乐趣",
	"phenomenon: n. 杰出的人或事, 现象",
	"essential: adj. 至关重要的",
	"essentially: adv. 本质上的",
	"prospect: n. 前景, 前途, 景色",
	"outlook: n. 景色, 风光",
	"interact: v. 互相作用, 交流",
	"interaction: n. 互相作用, 交流, 交往",
	"religious: adj. 宗教的",
	"ritual: n. 仪式, 老规矩, 例行公事  adj. 例行的",
	"ceremony: n. 典礼, 仪式, 礼节",
	"sacred: adj. 神圣的, 宗教的, 庄严的",
	"preach: v. 宣讲, 鼓吹, 宣传",
	"dean: n. 院长, 教长, 系主任 ",
	"pilgrim: n. 朝圣者",
	"stimulate: v. 刺激, 激发, 促使",
	"stimulus: n. 刺激, 促进因素, 刺激物",
	"assimilative: adj. 同化的",
	"assimilation: n. 消化, 接收, 吸收",
	"imitate: v. 模仿, 消防队",
	"resemble: v. 类似于",
	"analogy: n. 类比, 比拟",
	"analogous: adj. 相似的, 类似的",
	"tease: v. 戏弄, 挑逗",
	"tear: v. 撕裂, 撕破",
	"await: v. 等候, 即将发生",
	"typewriter: n. 打字机",
	"stereotype: n. 刻板印象",
	"appeal: v. 呼吁, 恳求, 有吸引力, 申诉, 上诉",
	"conceal: v. 隐瞒, 掩盖",
	"zeal: n. 热情, 热忱",
	"automobile: n. 汽车",
	"automotive: adj. 汽车的",
	"bias: n. 偏见  v. 使有偏见",
	"constitution: n. 宪法, 章程, 体格, 体质, 构成",
	"constitutional: adj. 宪法的, 体质上的",
	"constitute: v. 组成, 构成",
	"constituent: adj. 组成的, 构成的",
	"substitute: n. 代替物  v. 用...代替",
	"temper: n. 脾气, 怒气, 心情",
	"tempered: adj. 有脾气的",
	"temperament: n. 性情, 气质",
	"eve: n. 前夕",
	"ultimate: adj. 最后的, 最终的, 根本的",
	"affiliation: n. 联系, 从属关系",
	"oppose: v. 反对, 阻挠",
	"opposed: adj. 反对的",
	"opposing: adj. 相反的, 对立的",
	"opposite: adj. 对面的, 另一边的  n. 对立面",
	"opponent: n. 对手, 反对者",
	"contradict: v. 反驳, 同...矛盾, 同...相抵触",
	"contradictory: adj. 反驳的, 反对的",
	"incompatible: adj. 不协调的, 不兼容的",
	"addict: n. 对...入迷的人, 有瘾的人  v. 使成瘾, 使入迷",
	"addicted: adj. 有瘾的, 上瘾的, 痴迷的",
	"addiction: n. 上瘾, 沉溺",
	"dedicate: v. 奉献, 把...用在",
	"verdict: v. 裁定, 判决",
	"anticipate: v. 预料, 预期",
	"anticipation: n. 期待, 预期, 预计",
	"shortcoming: n. 缺点, 短处",
	"shorthand: n. 速记",
	"supreme: adj. 极度的, 最高的",
	"superb: adj. 极好的, 卓越的",
	"superiority: n. 优越, 优势, 优势感",
	"superstition: n. 迷信",
	"superficial: adj. 表面的, 肤浅的",
	"variety: n. 变化, 多样化, 种类",
	"vary: v. 变化, 改变, 使不同",
	"varied: adj. 各式各样的",
	"varying: adj. 不同的, 有差异的",
	"variable: adj. 多变的, 易变的  n. 变量, 可变因素",
	"variation: n. 变化, 差异",
	"reluctant: adj. 不情愿的",

	//15
	"aspect: n. 方面, 层面",
	"retrospect: v. 回顾, 回想",
	"speculate: v. 推测, 投机",
	"spectrum: n. 光谱, 范围, 系列",
	"blaze: n. 火焰, 火光",
	"boost: v. 提高, 促进",
	"boast: v. 夸, 夸大, 自夸",
	"boom:  n. 繁荣, 轰",
	"booming: n. 繁荣  adj. 蓬勃发展的",
	"boot: n. 靴子  v. 启动",
	"booth: n. 摊位, 岗亭",
	"soar: adj. 增长的",
	"celebrity: n. 名人",
	"celebrate: v. 庆祝, 庆贺, 表扬",
	"mortal: n. 凡人  adj. 致命的",
	"mortality: n. 死亡率",
	"debate: v. 争论, 争辩",
	"combat: v. 战斗, 斗争",
	"struggle: v. 斗争, 竞争",
	"pound: v. 击碎  n. 英镑",
	"dispute: v. 争论, 辩论",
	"disputable: adj. 有争议的, 未确定的",
	"undesirable: adj. 不受欢迎的, 不良的",
	"devise: v. 设计, 发明, 想出",
	"delight: v. 使快乐, 使高兴  n. 快乐, 愉快",
	"tight: adj. 紧密的, 紧的  adv. 紧紧地",
	"enlighten: v. 启迪, 启发",
	"nasty: adj. 讨厌的, 卑劣的",
	"phrase: n. 短语, 词组",
	"phase: n. 阶段, 时期",
	"psychological: n. 心理学的",
	"psychiatry: n. 精神病学",
	"auction: n/v. 拍卖",
	"refer: v. 参考, 参照",
	"confer: v. 授予, 商谈",
	"conference: n. 会议",
	"reputation: n. 名誉, 声誉",
	"prestige: n. 声望, 威望",
	"revive: v. 复活, 复兴",
	"revival: n. 复兴",
	"advisory: adj. 咨询的, 顾问的  n. 咨询",
	"charter: n. 章程, 宪章  v. 租",
	"collective: n. 集体, 团体  adj. 集体的, 共同的",
	"elect: v. 选举, 推举",
	"eligible: adj. 有资格当选的, 合格的",

	// 16
	"coupon: n. 礼券, 票证",
	"infant: n. 婴儿, 幼儿",
	"rare: adj. 少见的, 稀罕的",
	"symptom: n. 症状, 症候, 征兆",
	"bacterial: adj. 细菌的",
	"literary: adj. 文学的",
	"favour: n. 恩惠, 赞同, 支持  v. 支持, 偏爱",
	"favorable: adj. 有利的, 赞许的",
	"fuel: n. 燃料  v. 增加, 加强",
	"historical: adj. 历史的, 过去的",
	"historic: adj. 历史有名的",
	"historian: n. 历史学家",
	"prehistoric: adj. 史前的",
	"fossil: n. 化石",
	"archaeological: adj. 考古学的",
	"archaeologist: n. 考古学家",
	"persist: v. 坚持不懈",
	"persistence: n. 坚持, 持续",
	"resist: v. 反抗, 抵抗",
	"resistant: adj. 抵抗的, 反抗的",
	"consist: v. 组成, 构成, 在于",
	"consistent: adj. 一致的, 持续的, 相符的",
	"consistently: adv. 一贯地",
	"assist: v. 援助, 帮助",
	"assistant: n. 助手  adj. 辅助的, 助理的",
	"assistance: n. 援助, 帮助",
	"boycott: n/v. 抵制, 拒绝参加",
	"defy: v. 违抗, 反抗, 挑战",
	"joint: n. 接头, 结合处, 关节  adj. 联合的, 共同的, 连接的",
	"jointly: adv. 共同地, 连带地",
	"adjoin: v. 毗邻",
	"adjoining: adj. 隔壁的, 邻接的",
	"conjunction: n. 连接, 结合, 连接词",
	"maintain: v. 维持, 保持",
	"attain: v. 获得, 实现, 达到",
	"obtain: v. (困难时期)获得, 得到",
	"retain: v. 保留, 保持",
	"retention: n. 保留, 保持, 保留物, 记忆力",
	"entertain: v. 款待, 请客",
	"entertaining: adj. 愉快的, 娱乐性的, 有趣的  n. 宴请, 招待",
	"sustain: v. 维持, 保持, 经受, 支持, 支撑, 证实",
	"sustainable: adj. 可持续的",
	"sustained: adj. 持续的",
	"sustainability: n. 持续性",
	"marital: adj. 婚姻的",
	"intermarriage: n. 近亲结婚, 联姻, 异族结婚",
	"enormous: adj. 巨大的, 很多的",
	"norm: n. 规范, 准则",
	"gigantic: adj. 巨大的",
	"tremendous: adj. 巨大的",
	"objection: n. 反对, 异议",
	"objectiveness: n. 客观, 客观性",
	"apparent: adj. 显而易见的, 明显的, 表面的",
	"apparently: adv. 显然地",
	"recur: v. 再发生",
	"incur: v. 带来, 遭受, 招致",
	"originate: v. 起源, 创始, 开创, 引起",
	"derive: v. 取得, 起源, 来自",
	"circulation: n. 发行量, 销售量",
	"overlook: v. 忽视, 宽容",
	"overlooked: adj. 被忽视的, 被忽略的",
	"overseas: adj. 海外的, 国外的",
	"overtime: n. 加班",
	"overburdened: adj. 负担过重的",
	"overwhelm: v. 征服, 制服, 难以承受",
	"overwhelming: adj. 压倒性的, 极强烈的",
	"parade: n. 游行, 阅兵  v. 游行, 展示",
	"refrain: v. 抑制, 克制  n. 反复说的话, 老调",
	"hamper: v. 妨碍, 阻碍",
	"hinder: v. 妨碍, 阻碍",
	"prime: n. 青春, 壮年  adj. 首要的, 主要的  v. 使准备好",
	"primitive: adj. 原始的, 上古的",
	"reflect: v. 反射, 反映, 考虑, 深思",
	"inhale: v. 吸入",
	"specify: v. 明确指定, 具体说明",
	"stock: n. 股票, 备料  v. 储备",
	"stockpile: n. 储备",
	"inventory: n. 目录, 库存, 清单",

	// 17
	"",
	"",
}
